owner: devtrusttest
repo: website-uptime-monitor

sites:
  - name: DevTrust Main Site
    url: https://devtrust.biz
  - name: RDT API
    url: https://rdt-api.devtrust.biz
  - name: Seller OpenAI
    url: https://seller-openai.devtrust.biz
  - name: PCM URL Check
    url: https://pcm-url-check.devtrust.biz
  # Add all 50+ websites here

status-website:
  # cname: status.devtrust.biz  # Optional: custom domain
  logoUrl: https://devtrust.biz/_next/static/media/devtrust-logo.0ee0a186.svg
  name: DevTrust Status
  introTitle: "Website Uptime Monitor"
  introMessage: Real-time status for all DevTrust services
  
# Notification settings
notifications:
  - type: email
    address: shivam.k@devtrust.biz
  - type: slack
    webhookUrl: $SLACK_WEBHOOK_URL
